repositories {
    mavenLocal()
    mavenCentral()

    maven {
        name 'CurseMaven'
        url 'https://cursemaven.com'
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name 'Modrinth'
        url 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }

    maven {
        name "Tterrag"
        url "https://modmaven.dev/"
        content {
            includeGroup("com.tterrag.registrate")
        }
    }
    maven { // Mixin²
        url "https://maven.bawnorton.com/releases"
        content {
            includeGroup "com.github.bawnorton.mixinsquared"
        }
    }

}