repositories {
    mavenLocal()
    mavenCentral()

    // Curseforge
    maven {
        name 'CurseMaven'
        url 'https://cursemaven.com'
        content {
            includeGroup "curse.maven"
        }
    }

    // Modrinth
    maven {
        name 'Modrinth'
        url 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }

    // Registrate
    maven {
        name "Tterrag"
        url "https://modmaven.dev/"
        content {
            includeGroup("com.tterrag.registrate")
        }
    }

    // Mixin²
    maven {
        url "https://maven.bawnorton.com/releases"
        content {
            includeGroup "com.github.bawnorton.mixinsquared"
        }
    }

    // Configuration
    maven {
        name 'Configuration'
        url 'https://repo.repsy.io/mvn/toma/public/'
    }
    maven {
        name 'Configuration (alternative/backup)'
        url 'https://api.repsy.io/mvn/toma/public/'
    }

    // EMI
    repositories {
        maven {
            name = "TerraformersMC"
            url = "https://maven.terraformersmc.com/"
        }
    }

    maven { //GTM maven
        name = 'GTCEu Maven'
        url = 'https://maven.gtceu.com'
        content {
            includeGroup 'com.gregtechceu.gtceu'
            includeGroup 'appeng'
        }
    }
}