# Gradle Properties
org.gradle.jvmargs                  = -Xmx8G -Dnet.minecraftforge.gradle.test_certs=false -Djline.terminal=dumb
org.gradle.parallel                 = true
org.gradle.logging.stacktrace       = all

# Mod Information
# HIGHLY RECOMMEND complying with SemVer for mod_version: https://semver.org/
mod_version                         = 0.1.1
mod_version_type                    = release
mod_package                         = team.terrafirmagreg.jellies
mod_id                              = jellies
mod_name                            = Jellies
mod_name_suffix                     = 1.20.1

# Mod Metadata (Optional)
mod_description                     = Jellies of TerraFirmaGreg.
mod_url                             = https://www.curseforge.com/minecraft/mc-mods/jellies

# Delimit authors with commas
mod_authors                         = Sakura et. al.
mod_credits                         = TerraFirmaGreg-Team.
mod_logo_path                       = /logo.png

# Mapping Properties
mapping_channel                     = parchment
mapping_version                     = 2023.09.03-1.20.1
use_dependency_at_files             = true

# The Minecraft version the Parchment version is for
neoForge.parchment.minecraftVersion = 1.20.1
# The version of the Parchment mappings
neoForge.parchment.mappingsVersion  = 2023.09.03

# Run Configurations
# If multiple arguments/tweak classes are stated, use spaces as the delimiter
minecraft_version                   = 1.20.1
minecraft_username                  = Developer

### Dependency versions

# Build environment
java_version                        = 17
gradle_version                      = 8.12.1
mdg_legacy_version                  = 2.0.119
spotless_version                    = 7.2.1

# Forge
loader                              = forge
forge_version                       = 47.4.13
loader_version_range                = [47,)

# Dependencies
emi_version                         = 1.1.22+1.20.1
tfc_version                         = 3.2.22
ad_astra_version                    = 1.15.20
beneath_version                     = 1.0.6
gtm_version                         = 7.5.3
